# Generated by Django 5.0.6 on 2024-06-29 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_admintags_blogpost_admin_award_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='admin_award_tags',
        ),
        migrations.DeleteModel(
            name='AdminTags',
        ),
    ]
