# Generated by Django 5.0.6 on 2024-06-29 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_alter_tag_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminlabel',
            name='created_by',
        ),
    ]
